DROP TABLE CUSTOMER IF EXISTS ;

CREATE TABLE CUSTOMER (
  ID UUID NOT NULL,
  TITLE VARCHAR(255),
  IS_DELETED BOOLEAN  NOT NULL  DEFAULT FALSE,
  CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);

CREATE INDEX IDX_CUSTOMER_ID_IS_DELETED ON CUSTOMER(ID, IS_DELETED);